// Math Object
let result;

// PI Number
result = Math.PI

// round method()
result = Math.round(9.5)
result = Math.round(9.4)

// power method()
result = Math.pow(9,2)

// Find square root of a number
result = Math.sqrt(64)
result = Math.sqrt(32)
result = Math.sqrt(16)
result = Math.sqrt(8)

// Absolute positive 
result = Math.abs(-10)
result = Math.abs(9)
result = Math.abs("-1")

// Sin-Cos
result = Math.sin(90*Math.PI/180)
result = Math.cos(0*Math.PI/180)

// floor - ceil method

result = Math.floor(9.5)
//result = Math.round(9.5)
//result = Math.ceil(9.5)

// generate numbers with random() method

result =  Math.random(); // 0.1 - 0.9
result = Math.random()*10 - 0-9
result = Math.floor(Math.random()*10) // 0-9
result = Math.floor(Math.random()*11) // 1-10

let numbers =[]

function GenNumbers(min,max){
    let number = Math.floor(Math.random()*((max-min)+1)+min)
    console.log("Random Number",number);
    return number;
}

for(let i=0;i<10;i++){
    let number = GenNumbers(1,5);
    numbers.push(number)
}


console.log(numbers);

//console.log(result);


// What you'll need
/*
html side:
input element type as number
button element

js side:
select input.value with getElementById()
callback function for onClick event
if else - to check input.value is equal to the number generated by Math.random()
if yes print posiive msg
if not then print("try again")


*/

STEP1
